// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VoltSense.Infrastructure.Persistence;

#nullable disable

namespace VoltSense.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(VoltSenseDbContext))]
    partial class VoltSenseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VoltSense.Domain.Entities.ConnectionEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpsDeviceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UpsDeviceId", "OccurredAt")
                        .HasDatabaseName("ix_connection_events_device_occurred_at");

                    b.ToTable("connection_events", (string)null);
                });

            modelBuilder.Entity("VoltSense.Domain.Entities.TelemetrySnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("BatteryCharge")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("BatteryVoltage")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Frequency")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("InputVoltage")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("LoadPercentage")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("OutputVoltage")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Power")
                        .HasColumnType("numeric");

                    b.Property<int?>("RuntimeSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpsDeviceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UpsDeviceId", "Timestamp")
                        .HasDatabaseName("ix_telemetry_snapshots_device_timestamp");

                    b.ToTable("telemetry_snapshots", (string)null);
                });

            modelBuilder.Entity("VoltSense.Domain.Entities.UpsDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("ConnectionType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirmwareVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("FirstDetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VendorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_ups_devices_is_active");

                    b.HasIndex("VendorId", "ProductId", "SerialNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_ups_devices_natural_key");

                    b.ToTable("ups_devices", (string)null);
                });

            modelBuilder.Entity("VoltSense.Domain.Entities.ConnectionEvent", b =>
                {
                    b.HasOne("VoltSense.Domain.Entities.UpsDevice", "UpsDevice")
                        .WithMany("ConnectionEvents")
                        .HasForeignKey("UpsDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UpsDevice");
                });

            modelBuilder.Entity("VoltSense.Domain.Entities.TelemetrySnapshot", b =>
                {
                    b.HasOne("VoltSense.Domain.Entities.UpsDevice", "UpsDevice")
                        .WithMany("TelemetrySnapshots")
                        .HasForeignKey("UpsDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UpsDevice");
                });

            modelBuilder.Entity("VoltSense.Domain.Entities.UpsDevice", b =>
                {
                    b.Navigation("ConnectionEvents");

                    b.Navigation("TelemetrySnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
